### ISSUE TITLE
__init__.py doesn't support callbacks class

### ISSUE THREAD

**Issue by tbeam915** [simplyequipped/pyjs8call#1]
please add 
from pyjs8call.clients import Callbacks 

into __init__.py

**Comment by simplyequipped** [comment]
Thanks for pointing this out. client.Callbacks and client.Settings have been added to __init__.py in the develop branch. The change will be merged into the main branch in version 0.2.2.

If you have additional questions, I recommend opening a [discussion](https://github.com/simplyequipped/pyjs8call/discussions) so others can benefit from the discussion as well.
